wheel_radius: 0.25
wheel_width: 0.137
wheel_base: 1.6 # between front wheel center and rear wheel center
wheel_tread: 1.3 # between left wheel center and right wheel center
front_overhang: 0.5 # between front wheel center and vehicle front
rear_overhang: 0.5 # between rear wheel center and vehicle rear 
left_overhang: 0.1 # between left wheel center and vehicle left
right_overhang: 0.1 # between right wheel center and vehicle right
vehicle_height: 1.7
min_height_offset: -0.5 
max_height_offset: 1.5
max_steer_angle: 0.5236 # in radians
